
TOTAL_MATRIX_ROWS = 16
TOTAL_MATRIX_COLS = 48
TOTAL_MATRIX_LEDS = TOTAL_MATRIX_ROWS * TOTAL_MATRIX_COLS


SINGLE_MATRIX_ROWS = 16
SINGLE_MATRIX_COLS = 16
SINGLE_MATRIX_LEDS = SINGLE_MATRIX_ROWS * SINGLE_MATRIX_COLS

PIN = 15

ASCII_WIDTH = 6
ASCII_HEIGHT = 6